name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  build:
    name: 'Skip: ${{matrix.skip}} (${{matrix.hhvm}})'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        skip: [ true, false ]
        hhvm:
          - "4.102"
          - "4.128"
          - "4.153"
          - "4.168"
    runs-on: ${{matrix.os}}-20.04
    steps:
      - uses: actions/checkout@v2
      # No way to set working directory for a GitHub Action :(
      - name: Move test files to repository root
        shell: bash
        run: |
          shopt -s dotglob
          mv test-project/* .
      - name: Standard run
        uses: ./hack-lint-test
        with:
          hhvm: ${{matrix.hhvm}}
          skip_lint: ${{matrix.skip}}
          skip_tests: ${{matrix.skip}}
      - name: Override HHVM flags
        uses: ./hack-lint-test
        with:
          hhvm: ${{matrix.hhvm}}
          hhvm_flags: -dhhvm.hack.lang.enable_coeffects=true -dhhvm.forbid_division_by_zero=true
          skip_lint: ${{matrix.skip}}
          skip_tests: ${{matrix.skip}}
